# Linear Algebra

In [20]:
import numpy as np

### 1. Matrix Operation

In [9]:
mat_A= [[2, -1], [0, 3]]
mat_B= [[1, 2], [-3, 4]]
print(" A + B : \n", np.array(mat_A)+np.array(mat_B))
print("\n A . B : \n", np.dot(mat_A, mat_B))
print("\n 3A - 2B : \n", np.dot(mat_A, 3)-np.dot(B, 2))

 A + B : 
 [[ 3  1]
 [-3  7]]

 A . B : 
 [[ 5  0]
 [-9 12]]

 3A - 2B : 
 [[ 4 -7]
 [ 6  1]]


### 2. Determinants and Inverses

In [46]:
mat_A= [[2, -1], [0, 3]]
det_A = np.linalg.det(mat_A) 
print("Determinant of matrix A: ", det_A)
if det_A != 0:    
    inv_A = np.linalg.inv(mat_A)
    print("Inverse of matrix A: \n", inv_A) 
else:
    print("Not invertible")

Determinant of matrix A:  6.0
Inverse of matrix A: 
 [[0.5        0.16666667]
 [0.         0.33333333]]


### 3. Eigen values and Eigen vectors

In [18]:
mat_C = [[4, 1], [-2, 1]]
evalue, evector = np.linalg.eig(mat_C)
print("Eigenvalue: ", evalue)
print("Eigenvector: ", evector)
        

Eigenvalue:  [3. 2.]
Eigenvector:  [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [47]:
mat_X = np.array([[4, 1.5, 100],
         [6, 2.0, 150]]) #dataset for car1 and car2
mat_Y = np.array([20, 30]) #price for car1 and car2
beta = np.linalg.pinv(mat_X) @ mat_Y #using psudoinv for numerical stability
car3 = np.array([8, 3.0, 200]) #dataset for car3
car3_price = car3 @ beta #predicting price of car3 by doing dot product of car3 and beta
print("The price of car 3 is ", car3_price)

The price of car 3 is  40.00000000000002


## Discussion and Conclusion

Through this lab sesion, we wee able to be familiar with the concept of linear algebra, specifically matrix, in Python. We were able to perform basic matrix operation, such as addition, dot product, determinants and inverses. We were also able to learn how to compute eigenvalues and eigenvectos using the numpy library functions.

We were also given a dataset about cars and instructed to use the concept of coefficient vector to predict the price of car3 using the dataset. Here, we used the concept of 'pseudoinverse' to compute the coefficient vector since the feature matrix "mat_X" is not directly invertible as it is not a square matrix. For this, we used the numpy library function 'np.linalg.pinv(mat_X)', after which the price of car3 was then predicted from the given dataset.

In Conclusion, we were able to use the numpy library functions to perform basic matrix operations and then further increase our knowledge by applying the basics and numpy library functions to perform real time data analysis from a given dataset.